# Generated by Django 3.0.6 on 2020-05-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('team_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('xxs', models.IntegerField(default=0)),
                ('xs', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('m', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('xl', models.IntegerField(default=0)),
                ('xxl', models.IntegerField(default=0)),
                ('xxxl', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Womens'), ('U', 'Unisex')], default='U', max_length=1)),
                ('itemtype', models.CharField(choices=[('hoodie', 'hoodie'), ('tshirt', 'tshirt'), ('jersey', 'jersey'), ('bibs', 'bibs'), ('vest', 'vest'), ('armwarmers', 'armwarmers'), ('jacket', 'jacket'), ('cap', 'cap'), ('gloves', 'gloves'), ('water bottle', 'water bottle'), ('pedals', 'pedals'), ('wheels', 'wheels'), ('bag', 'bag'), ('bike', 'bike'), ('bags', 'bags'), ('miscellaneous', 'miscellaneous')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('TEAM', 'Team'), ('RETAIL', 'Retail')], max_length=6)),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('size', models.CharField(choices=[('XXS', 'Xxs'), ('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl')], max_length=5, verbose_name='Item size')),
                ('date', models.DateField(verbose_name='date of sale')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_check.Item')),
            ],
        ),
        migrations.CreateModel(
            name='enRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xxs', models.IntegerField(default=0)),
                ('xs', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('m', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('xl', models.IntegerField(default=0)),
                ('xxl', models.IntegerField(default=0)),
                ('xxxl', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_check.Item')),
            ],
        ),
    ]
