# Generated by Django 3.0.6 on 2020-05-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enRoute',
            new_name='Coming',
        ),
    ]
