# Generated by Django 3.0.6 on 2020-05-20 01:37

from django.db import migrations, models
import inv_check.models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0002_auto_20200518_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=inv_check.models.Item.current_year, verbose_name='year item is added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('W', 'Womens'), ('U', 'Unisex')], default='U', max_length=1),
        ),
    ]
