# Generated by Django 3.0.6 on 2020-05-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0004_auto_20200520_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='forSale',
            field=models.BooleanField(default=True, verbose_name='Is item for sale? '),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0, verbose_name='If no sizes, enter count'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Receipt $ amount '),
        ),
        migrations.AlterField(
            model_name='sale',
            name='size',
            field=models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('count', 'COUNT')], max_length=5, verbose_name='Sold item size (if no size, select count) '),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('count', 'COUNT')], max_length=5, verbose_name='Sold item size (if no size, select count) ')),
                ('quantity', models.IntegerField(default=1)),
                ('recipient', models.CharField(choices=[('TEAM MEMBER', 'Team'), ('RETAIL', 'Retail')], max_length=11)),
                ('date', models.DateField(verbose_name='date of order')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(default='', max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=3)),
                ('zip', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_check.Item')),
            ],
        ),
    ]
