# Generated by Django 3.0.6 on 2020-05-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0005_auto_20200521_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient',
            field=models.CharField(choices=[('TEAM MEMBER', 'Team'), ('RETAIL', 'Retail')], default='RETAIL', max_length=11),
        ),
        migrations.AlterField(
            model_name='sale',
            name='size',
            field=models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('count', 'COUNT')], max_length=5, verbose_name='Item size (if no size, select count) '),
        ),
    ]
