# Generated by Django 3.0.6 on 2020-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0007_auto_20200521_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgurl_1',
            field=models.URLField(default='https://drive.google.com/file/d/1WZFyFdPikqZtkAI1KtvgmMJzJBzNHT8U/view?usp=sharing', verbose_name='Image of item'),
        ),
        migrations.AddField(
            model_name='item',
            name='imgurl_2',
            field=models.URLField(default='https://drive.google.com/file/d/1WZFyFdPikqZtkAI1KtvgmMJzJBzNHT8U/view?usp=sharing', verbose_name='Image of item'),
        ),
    ]
