# Generated by Django 3.0.6 on 2020-05-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0008_auto_20200524_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imgurl_2',
        ),
    ]
