# Generated by Django 3.0.6 on 2020-05-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0009_remove_item_imgurl_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imgurl_1',
            field=models.URLField(default='https://drive.google.com/uc?id=1WZFyFdPikqZtkAI1KtvgmMJzJBzNHT8U', verbose_name='Image of item'),
        ),
    ]
