# Generated by Django 3.0.6 on 2020-05-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0010_auto_20200524_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.CharField(choices=[('hoodie', 'hoodie'), ('tshirt', 'tshirt'), ('jersey', 'jersey'), ('bibs', 'bibs'), ('vest', 'vest'), ('armwarmers', 'armwarmers'), ('jacket', 'jacket'), ('cap', 'cap'), ('gloves', 'gloves'), ('water bottle', 'water bottle'), ('pedals', 'pedals'), ('wheels', 'wheels'), ('bags', 'bags'), ('bike', 'bike'), ('bags', 'bags'), ('miscellaneous', 'miscellaneous'), ('socks', 'socks'), ('wheels', 'wheels')], max_length=13),
        ),
    ]
