# Generated by Django 3.0.6 on 2020-08-04 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0013_item_itemcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('count', 'COUNT')], max_length=5, verbose_name='Item size'),
        ),
        migrations.CreateModel(
            name='itemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('count', 'COUNT')], max_length=5, verbose_name='Item size')),
                ('quantity', models.IntegerField(default=1)),
                ('recipient', models.CharField(choices=[('TEAM MEMBER', 'Team'), ('RETAIL', 'Retail')], default='RETAIL', max_length=11)),
                ('date', models.DateField(auto_now_add=True, verbose_name='date of order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_check.Item')),
            ],
        ),
    ]
