# Generated by Django 3.0.6 on 2020-08-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv_check', '0014_auto_20200803_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemOrder',
        ),
    ]
